package com.knapsack.fixtool.ui.diff

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.toAwtImage
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.captureToImage
import androidx.compose.ui.test.isRoot
import androidx.compose.ui.test.junit4.ComposeContentTestRule
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onFirst
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performTextReplacement
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.knapsack.fixtool.model.FixDictionaryAdapter
import com.knapsack.fixtool.model.FixVersion
import com.knapsack.fixtool.model.scenario.Expectation
import com.knapsack.fixtool.model.scenario.FieldExpectation
import com.knapsack.fixtool.model.scenario.MatchMode
import com.knapsack.fixtool.model.scenario.Matcher
import com.knapsack.fixtool.model.scenario.TemporalKind
import com.knapsack.fixtool.service.MessageView
import com.knapsack.fixtool.service.compare.ReferenceMessage
import com.knapsack.fixtool.service.wireView
import com.knapsack.fixtool.ui.AppTheme
import org.junit.Rule
import org.junit.Test
import java.io.File
import java.time.Instant
import javax.imageio.ImageIO

/**
 * **The fix gallery: one picture per repair the surface offers, before and after.**
 *
 * These are living documentation, regenerated by every test run into `build/scenario-screenshots/` —
 * `fixes_NN_<kind>_offer.png` shows the affordance on the failure it repairs, `fixes_NN_<kind>_applied.png`
 * shows the surface after one click. Each test asserts the affordance exists before photographing it, so a
 * renamed tag or a withdrawn offer fails the build loudly instead of silently producing a gallery of
 * yesterday's UI. (Screenshots caught D1 when no assertion did — the argument for keeping pictures in the
 * suite at all. Tooltip text is deliberately absent here: tooltips need a hover the harness cannot hold
 * through a capture, and their wording is pinned by ReconcileSessionTest instead.)
 *
 * Fixtures are deliberately minimal — two to seven rows — so each image is about exactly one thing.
 */
class FixGalleryScreenshotTest {
    @get:Rule
    val composeTestRule = createComposeRule()

    private val dictionary = FixDictionaryAdapter.forVersion(FixVersion.FIX_4_4)
    private val arrival: Instant = Instant.parse("2026-07-14T09:35:44Z")
    private val outDir = File("build/scenario-screenshots").absoluteFile

    private fun ComposeContentTestRule.surface(
        initial: Expectation,
        message: MessageView,
        height: Dp = 340.dp,
    ) {
        setContent {
            var expectation by remember { mutableStateOf(initial) }
            val session =
                remember(Unit) {
                    ReconcileSession(
                        original = expectation,
                        initialReference =
                            ReferenceMessage.live(
                                message,
                                ReferenceMessage.Provenance.THIS_RUN,
                                "received — this run · 09:35:44",
                                arrival,
                            ),
                        dictionary = dictionary,
                        onChange = { expectation = it },
                    )
                }
            Box(modifier = Modifier.size(1180.dp, height).background(AppTheme.Colors.background)) {
                DiffSurface(session, crumb = "fix gallery › Step 2 · Expect ExecutionReport (8)")
            }
        }
    }

    private fun snap(name: String) {
        try {
            outDir.mkdirs()
            // The FIRST root: an open autocomplete popup (07's tag picker) is a second root window, and
            // onRoot() refuses to choose. The surface's own window is always the first.
            val image = composeTestRule.onAllNodes(isRoot()).onFirst().captureToImage()
            ImageIO.write(image.toAwtImage(), "png", File(outDir, "$name.png"))
        } catch (e: Exception) {
            println("[FixGallery] snapshot '$name' skipped: ${e.message}")
        }
    }

    private fun open(vararg fields: FieldExpectation) =
        Expectation(fields.toList(), messageType = "8", mode = MatchMode.OPEN)

    private fun click(tag: String) {
        composeTestRule.onNodeWithTag(tag).assertIsDisplayed()
        composeTestRule.onNodeWithTag(tag).performClick()
        composeTestRule.waitForIdle()
    }

    /** `«` on a value mismatch: re-baseline to what actually arrived, keeping the kind of matcher it is. */
    @Test
    fun `01 accept actual`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8")), FieldExpectation(151, Matcher.Numeric(0.0))),
            wireView(35 to "8", 151 to "500000"),
        )
        composeTestRule.onNodeWithTag("accept_actual-151-0").assertIsDisplayed()
        snap("fixes_01_accept_actual_offer")
        click("accept_actual-151-0")
        snap("fixes_01_accept_actual_applied")
    }

    /** `±` on numeric drift: the smallest band covering both sides, around the author's own baseline. */
    @Test
    fun `02 loosen to a covering band`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8")), FieldExpectation(44, Matcher.Exact("2.0"))),
            wireView(35 to "8", 44 to "1.9"),
        )
        composeTestRule.onNodeWithTag("loosen-44-0").assertIsDisplayed()
        snap("fixes_02_loosen_offer")
        click("loosen-44-0")
        snap("fixes_02_loosen_applied")
    }

    /** `×` on a failing row, error-red: one of the repairs. The step stops checking the tag. */
    @Test
    fun `03 drop a failing row`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8")), FieldExpectation(58, Matcher.Exact("filled"))),
            wireView(35 to "8", 58 to "partial"),
        )
        composeTestRule.onNodeWithTag("drop-58-0").assertIsDisplayed()
        snap("fixes_03_drop_failing_offer")
        click("drop-58-0")
        snap("fixes_03_drop_failing_applied")
    }

    /** `×` on a GREEN row, muted: authoring-delete on a fresh capture — housekeeping, not an alarm. */
    @Test
    fun `04 drop a passing row`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8")), FieldExpectation(15, Matcher.Exact("USD"))),
            wireView(35 to "8", 15 to "USD"),
        )
        composeTestRule.onNodeWithTag("drop-15-0").assertIsDisplayed()
        snap("fixes_04_drop_green_offer")
        click("drop-15-0")
        snap("fixes_04_drop_green_applied")
    }

    /** `∅` on a tag the venue stopped sending: absence becomes the asserted truth. */
    @Test
    fun `05 assert absent`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8")), FieldExpectation(58, Matcher.Exact("filled"))),
            wireView(35 to "8"),
        )
        composeTestRule.onNodeWithTag("assert_absent-58-0").assertIsDisplayed()
        snap("fixes_05_assert_absent_offer")
        click("assert_absent-58-0")
        snap("fixes_05_assert_absent_applied")
    }

    /** `«` on a field the reply carries that no row mentions: seeded from the dictionary, inserted where it pairs. */
    @Test
    fun `06 assert an unasserted extra`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8"))),
            wireView(35 to "8", 2376 to "Y"),
        )
        composeTestRule.onNodeWithTag("assert_it-2376-0").assertIsDisplayed()
        snap("fixes_06_assert_it_offer")
        click("assert_it-2376-0")
        snap("fixes_06_assert_it_applied")
    }

    /** "+ assert a tag…" — the absent assertion for a tag in NEITHER column, from the header. */
    @Test
    fun `07 add an absent assertion for a new tag`() {
        composeTestRule.surface(
            open(FieldExpectation(35, Matcher.Exact("8"))),
            wireView(35 to "8"),
        )
        click("diff-add-tag")
        composeTestRule.onNodeWithTag("diff-add-tag-field").performTextReplacement("58")
        composeTestRule.waitForIdle()
        snap("fixes_07_add_absent_tag_picker")
        click("diff-add-tag-confirm")
        snap("fixes_07_add_absent_tag_applied")
    }

    /** `⇄` on a proven move: the violet crossing, repaired atomically — and per-row fixes withheld (D1). */
    @Test
    fun `08 accept the venue's new order`() {
        composeTestRule.surface(
            open(
                FieldExpectation(453, Matcher.Exact("2")),
                FieldExpectation(448, Matcher.Exact("FIRMA")),
                FieldExpectation(447, Matcher.Exact("D")),
                FieldExpectation(452, Matcher.Exact("1")),
                FieldExpectation(448, Matcher.Exact("FIRMB")),
                FieldExpectation(447, Matcher.Exact("D")),
                FieldExpectation(452, Matcher.Exact("4")),
            ),
            wireView(
                453 to "2",
                448 to "FIRMB", 447 to "D", 452 to "4",
                448 to "FIRMA", 447 to "D", 452 to "1",
            ),
            height = 480.dp,
        )
        composeTestRule.onNodeWithTag("accept-new-order").assertIsDisplayed()
        snap("fixes_08_accept_new_order_offer")
        click("accept-new-order")
        snap("fixes_08_accept_new_order_applied")
    }

    /** A drifted price, a drifted fill, a reformatted quantity and a late timestamp — the fix plan's whole range. */
    private val drifted =
        open(
            FieldExpectation(35, Matcher.Exact("8")),
            FieldExpectation(6, Matcher.Exact("1.09244")),
            FieldExpectation(31, Matcher.Numeric(1.09244)),
            FieldExpectation(38, Matcher.Exact("1000000")),
            FieldExpectation(60, Matcher.Temporal(TemporalKind.NOW_WITHIN_TOLERANCE, 60)),
        )
    private val driftedReply =
        wireView(
            35 to "8",
            6 to "1.09139",
            31 to "1.09139",
            38 to "1000000.0",
            // Five minutes after the arrival instant the rows are judged at: outside ±60s, inside ±300s.
            60 to "20260714-09:40:44",
        )

    /** "± fix 4…" → the sheet: two covering bands, a formatting repair, a temporal rung — applied as ONE edit. */
    @Test
    fun `09 fix plan with covering bands`() {
        composeTestRule.surface(drifted, driftedReply, height = 460.dp)
        click("diff-fix-plan")
        composeTestRule.onNodeWithTag("diff-fix-row-60").assertIsDisplayed()
        snap("fixes_09_fix_plan_sheet")
        click("diff-fix-apply")
        snap("fixes_09_fix_plan_applied")
    }

    /** The knob: one uniform tolerance — and the rows it cannot reach are marked "stay red", never hidden. */
    @Test
    fun `10 fix plan with a uniform tolerance that does not reach everything`() {
        composeTestRule.surface(drifted, driftedReply, height = 460.dp)
        click("diff-fix-plan")
        composeTestRule.onNodeWithTag("diff-fix-tolerance").performTextReplacement("0.0001")
        composeTestRule.waitForIdle()
        composeTestRule.onNodeWithTag("diff-fix-still-red").assertIsDisplayed()
        snap("fixes_10_fix_plan_uniform_stays_red")
    }

    /** "Accept all shape changes": the gone tag asserted absent, the new tag asserted — values untouched. */
    @Test
    fun `11 accept every shape change`() {
        composeTestRule.surface(
            Expectation(
                listOf(
                    FieldExpectation(35, Matcher.Exact("8")),
                    FieldExpectation(58, Matcher.Exact("filled")),
                ),
                messageType = "8",
                mode = MatchMode.STRICT,
            ),
            wireView(35 to "8", 2376 to "Y"),
        )
        composeTestRule.onNodeWithTag("diff-accept-shape").assertIsDisplayed()
        snap("fixes_11_accept_all_shape_offer")
        click("diff-accept-shape")
        snap("fixes_11_accept_all_shape_applied")
    }

    /**
     * **The mixed failure — both bulk actions, together.** The venue dropped a tag, added a tag AND let two
     * values drift, which is what a real re-run looks like. Accept-all-shape takes the shape churn (one
     * edit), the fix plan takes the drift (one edit): two clicks, two footer lines, each its own ⌘Z — and
     * the order does not matter, because the two act on disjoint rows by construction.
     */
    @Test
    fun `13 shape churn and value drift repaired together`() {
        composeTestRule.surface(
            Expectation(
                listOf(
                    FieldExpectation(35, Matcher.Exact("8")),
                    FieldExpectation(6, Matcher.Exact("1.09244")),
                    FieldExpectation(151, Matcher.Numeric(0.0)),
                    FieldExpectation(58, Matcher.Exact("filled")),
                ),
                messageType = "8",
                mode = MatchMode.STRICT,
            ),
            wireView(35 to "8", 6 to "1.09139", 151 to "500000", 2376 to "Y"),
            height = 420.dp,
        )
        composeTestRule.onNodeWithTag("diff-accept-shape").assertIsDisplayed()
        composeTestRule.onNodeWithTag("diff-fix-plan").assertIsDisplayed()
        snap("fixes_13_mixed_failure_both_offers")

        click("diff-accept-shape")
        snap("fixes_13_mixed_failure_shape_accepted")

        click("diff-fix-plan")
        click("diff-fix-apply")
        snap("fixes_13_mixed_failure_both_applied")
    }

    /**
     * **The whole matcher vocabulary on one screen** — every kind a row can assert, green against the same
     * reply, plus the reference's amber third state. Not a fix, but the palette every fix writes into:
     * `exact`, `presence`, `absent`, `oneOf` (the value must be one of a set), `regex` (full-match — a
     * *contains* is `.*substring.*`), `numeric ± tolerance`, `temporal ~now`, and the cross-step `reference`.
     */
    @Test
    fun `14 the matcher vocabulary`() {
        composeTestRule.surface(
            open(
                FieldExpectation(35, Matcher.Exact("8")),
                FieldExpectation(11, Matcher.Regex("ORD-[0-9a-f]+")),
                FieldExpectation(17, Matcher.Reference("\${id0}")),
                FieldExpectation(37, Matcher.Presence),
                FieldExpectation(150, Matcher.OneOf(listOf("0", "1", "2"))),
                FieldExpectation(151, Matcher.Numeric(500000.0, 1000.0)),
                FieldExpectation(60, Matcher.Temporal(TemporalKind.NOW_WITHIN_TOLERANCE, 60)),
                FieldExpectation(58, Matcher.Absent),
            ),
            wireView(
                35 to "8",
                11 to "ORD-9f3a",
                17 to "EXEC1784207189117",
                37 to "FX1784206943508",
                150 to "2",
                151 to "499500",
                60 to "20260714-09:35:44",
            ),
            height = 420.dp,
        )
        composeTestRule.onNodeWithTag("matcher-150-0").assertIsDisplayed()
        snap("fixes_00_matcher_vocabulary")
    }

    /** "Re-seed from reference": the step rebuilt from the reply — with the echo reference kept, not flattened. */
    @Test
    fun `12 reseed from the reference`() {
        composeTestRule.surface(
            open(
                FieldExpectation(35, Matcher.Exact("8")),
                FieldExpectation(11, Matcher.Reference("\${id0}")),
                FieldExpectation(151, Matcher.Numeric(0.0)),
            ),
            wireView(35 to "8", 11 to "ORD-9f3a", 151 to "500000", 2376 to "Y"),
        )
        composeTestRule.onNodeWithTag("diff-reseed").assertIsDisplayed()
        snap("fixes_12_reseed_offer")
        click("diff-reseed")
        snap("fixes_12_reseed_applied")
    }
}
